name: Container test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        packageScope: [
          "@awesome-backup/mongodb",
          "@awesome-backup/postgresql"
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-app-${{ matrix.packageScope }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-app-${{ matrix.packageScope }}-
          ${{ runner.os }}-buildx-app-
    - name: Setup docker image tag
      id: tag
      run: |
        tag=`echo ${{ matrix.packageScope }}:latest | tr -d '@'`
        echo "::set-output name=TAG::$tag"
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        push: false
        build-args: |
          packageScope=${{ matrix.packageScope }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
        tags: ${{ steps.meta.outputs.tag }}
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  conatiner-test:
    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        testingTargetBaseName: [
          "mongodb",
          "postgresql"
        ]

    steps:
    - uses: actions/checkout@v2
    - uses: brpaz/structure-tests-action@v1.1.2
      with:
        image: awesome-backup/${{ matrix.testingTargetBaseName }}
        configFile: ./docker/test/${{ matrix.testingTargetBaseName }}/structure-tests.yml
