name: Container test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        packageScope: [
          "@awesome-backup/mongodb",
          "@awesome-backup/postgresql"
        ]

    steps:
    - uses: actions/checkout@master
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-app-${{ matrix.flavor }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-app-${{ matrix.flavor }}-
          ${{ runner.os }}-buildx-app-
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        push: false
        build-args: |
          packageScope=${{ matrix.packageScope }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
        tags: ${{ matrix.packageScope }}:latest
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  conatiner-test:
    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        packageScope: [
          "@awesome-backup/mongodb",
          "@awesome-backup/postgresql"
        ]

    steps:
    - uses: actions/checkout@master
    - uses: brpaz/structure-tests-action@v1.1.2
      with:
          image: ${{ matrix.packageScope }}:latest
          configFile: structure-tests.yaml
