name: Application test

on:
  push:
    branches-ignore: [stable]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
          cache: "yarn"
      - run: yarn install
      - run: yarn test
      - name: Archive coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: tmp/coverage
